version: "3.9"
services:
  img:
    build:
      context: .
      target: main
    image: basiccoin:latest
    command:
      - "echo"
      - "done"

  node1:
    image: basiccoin:latest
    command:
      - "/basiccoin"
      - "--addr=node1:21720"
      - "--miners=1"
      - "--minerPayoutAddr=9ced59c961a632e55732947d6d1cb3aeafb2ac0e0e974a4faaf640dc5e656edc"
      - "--httpPort=8080"
    ports:
      - 8080:8080

  node2:
    image: basiccoin:latest
    command:
      - "/basiccoin"
      - "--seed=node1:21720"

  node3:
    image: basiccoin:latest
    command:
      - "/basiccoin"
      - "--seed=node2:21720"
      - "--miners=1"
      - "--minerPayoutAddr=0c4738eb17afce8ab5151dcd57b3dc134ba80b2b33e8be38759347b4542303ec"

  node4:
    image: basiccoin:latest
    command:
      - "/basiccoin"
      - "--seed=node3:21720"
