version: "3.9"
services:
  basiccoin1:
    build: .
    command:
      - "/basiccoin"
      - "--localAddr=basiccoin1:21720"
    ports:
      - 21720:21720

  basiccoin2:
    build: .
    command:
      - "/basiccoin"
      - "--localAddr=basiccoin2:21720"
      - "--seedAddr=basiccoin1:21720"

  basiccoin3:
    build: .
    command:
      - "/basiccoin"
      - "--localAddr=basiccoin3:21720"
      - "--seedAddr=basiccoin1:21720"

  basiccoin4:
    build: .
    command:
      - "/basiccoin"
      - "--localAddr=basiccoin4:21720"
      - "--seedAddr=basiccoin1:21720"