version: "3.9"
services:
  img:
    build: .
    image: basiccoin:latest
    command:
      - "echo"
      - "done"

  node1:
    image: basiccoin:latest
    command:
      - "/basiccoin"
      - "--addr=node1:21720"
    ports:
      - 21720:21720

  node2:
    image: basiccoin:latest
    command:
      - "/basiccoin"
      - "--addr=node2:21720"
      - "--seed=node1:21720"

  node3:
    image: basiccoin:latest
    command:
      - "/basiccoin"
      - "--addr=node3:21720"
      - "--seed=node1:21720"

  node4:
    image: basiccoin:latest
    command:
      - "/basiccoin"
      - "--addr=node4:21720"
      - "--seed=node3:21720"
