version: "3.9"
services:
  img:
    build: .
    image: basiccoin:latest
    command:
      - "echo"
      - "done"

  node1:
    image: basiccoin:latest
    command:
      - "/basiccoin"
      - "--addr=node1:21720"
      - "--miners=1"
      - "--httpPort=8080"
    ports:
      - 8080:8080

  node2:
    image: basiccoin:latest
    command:
      - "/basiccoin"
      - "--seed=node1:21720"

  node3:
    image: basiccoin:latest
    command:
      - "/basiccoin"
      - "--seed=node2:21720"
      - "--miners=1"

  node4:
    image: basiccoin:latest
    command:
      - "/basiccoin"
      - "--seed=node3:21720"
