version: "3.9"
services:
  img:
    build:
      context: .
      target: main
    image: bcnode:latest
    command:
      - "echo"
      - "done"

  node1:
    image: bcnode:latest
    command:
      - "/bcnode"
      - "--dev"
      - "--listen=true"
      - "--addr=node1:21720"
      - "--miners=1"
      - "--payout=eeeeeed6bdacc4d88f6e07ba9070a3bcc1d1648cb8393ecb47bbe02235e48a5a"
      - "--http-wallet"
      - "--save-dir=/root/chain"
    ports:
      - 8080:80
    volumes:
      - /Users/levi/Desktop/devchain:/root/chain

  node2:
    image: bcnode:latest
    command:
      - "/bcnode"
      - "--dev"
      - "--listen=true"
      - "--seeds=node1:21720"
      - "--miners=1"
      - "--payout=1111116d16df90d775cc31093d9e6f55bdbb7373b77b7d2178d78eb0a6760e20"

  node3:
    image: bcnode:latest
    command:
      - "/bcnode"
      - "--dev"
      - "--listen=true"
      - "--seeds=node1:21720,node2:21720"
