version: "3.9"
services:
  img:
    build:
      context: .
      target: main
    image: bcnode:latest
    command:
      - "echo"
      - "done"

  node1:
    image: bcnode:latest
    command:
      - "/bcnode"
      - "--dev"
      - "--addr=node1:21720"
      - "--miners=1"
      - "--payout=0c4738eb17afce8ab5151dcd57b3dc134ba80b2b33e8be38759347b4542303ec"

  node2:
    image: bcnode:latest
    command:
      - "/bcnode"
      - "--dev"
      - "--seed=node1:21720"
    
  node3:
    image: bcnode:latest
    command:
      - "/bcnode"
      - "--dev"
      - "--seed=node1:21720"
  
  node4:
    image: bcnode:latest
    command:
      - "/bcnode"
      - "--dev"
      - "--seed=node1:21720"
  
  node5:
    image: bcnode:latest
    command:
      - "/bcnode"
      - "--dev"
      - "--seed=node4:21720"
    
  node6:
    image: bcnode:latest
    command:
      - "/bcnode"
      - "--dev"
      - "--seed=node4:21720"
  
  node7:
    image: bcnode:latest
    command:
      - "/bcnode"
      - "--dev"
      - "--seed=node4:21720"
  
  node8:
    image: bcnode:latest
    command:
      - "/bcnode"
      - "--dev"
      - "--seed=node7:21720"
