version: "3.9"
services:
  baseimage:
    build: .
    image: basiccoin:latest

  node1:
    image: basiccoin:latest
    command:
      - "/basiccoin"
      - "--localAddr=node1:21720"
    ports:
      - 21720:21720

  node2:
    image: basiccoin:latest
    command:
      - "/basiccoin"
      - "--localAddr=node2:21720"
      - "--seedAddr=node1:21720"

  node3:
    image: basiccoin:latest
    command:
      - "/basiccoin"
      - "--localAddr=node3:21720"
      - "--seedAddr=node1:21720"

  node4:
    image: basiccoin:latest
    command:
      - "/basiccoin"
      - "--localAddr=node4:21720"
      - "--seedAddr=node1:21720"
